/*DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
  isbn VARCHAR(250) PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  pages INT NOT NULL,
  year INT NOT NULL
);

DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  nationality VARCHAR(250) NOT NULL
);*/